export const RUN_STATES = [
  "created",
  "starting",
  "searching",
  "opening_job",
  "easy_apply",
  "fill_step",
  "submit_attempted",
  "submitted",
  "ready",
  "claimed",
  "running",
  "paused",
  "needs_user_input",
  "completed",
  "failed",
  "cancelled",
] as const;

export type RunState = (typeof RUN_STATES)[number];

export const RUN_EVENT_TYPES = [
  "run_created",
  "executor_recovery_prepared",
  "executor_claimed",
  "executor_started",
  "starting",
  "searching",
  "opening_job",
  "easy_apply",
  "fill_step",
  "submit_attempted",
  "submitted",
  "page_loaded",
  "job_discovered",
  "job_qualified",
  "job_deferred",
  "application_answers_planned",
  "application_prepared",
  "application_question_answered",
  "application_question_deferred",
  "application_submitted",
  "application_skipped",
  "user_input_required",
  "run_paused",
  "run_resumed",
  "run_completed",
  "run_failed",
  "run_cancelled",
] as const;

export type RunEventType = (typeof RUN_EVENT_TYPES)[number];

/**
 * Event types that may only originate from the extension's scoped executor
 * capability. The dashboard can never submit these directly.
 */
export const EXECUTOR_RUN_EVENT_TYPES = [
  "executor_started",
  "page_loaded",
  "job_discovered",
  "job_qualified",
  "easy_apply",
  "application_answers_planned",
  "application_prepared",
  "application_question_answered",
  "application_question_deferred",
  "application_submitted",
  "application_skipped",
  "user_input_required",
  "run_completed",
  "run_failed",
] as const;

export type ExecutorRunEventType = (typeof EXECUTOR_RUN_EVENT_TYPES)[number];

export interface ApplicationRun {
  id: string;
  userId: string;
  state: RunState;
  targetRole: string;
  targetLocation: string;
  createdAt: string;
  updatedAt: string;
}

export interface ApplicationRunEvent {
  id: string;
  runId: string;
  type: RunEventType;
  occurredAt: string;
  idempotencyKey: string;
  detail?: Record<string, string | number | boolean | null>;
}

export const CANDIDATE_FACT_STATUSES = [
  "not_specified",
  "yes",
  "no",
] as const;

export type CandidateFactStatus = (typeof CANDIDATE_FACT_STATUSES)[number];

export const AUTOPILOT_MODES = ["verified", "smart"] as const;

export type AutopilotMode = (typeof AUTOPILOT_MODES)[number];

/**
 * Candidate-controlled defaults for the moments where an application needs a
 * fact that is not already available. "Smart" may reuse grounded, approved
 * answers; it never authorizes inventing a candidate fact.
 */
export interface CandidateAutopilotPreferences {
  mode: AutopilotMode;
  answeringMode?: "competitive" | "conservative";
  questionTimeoutSeconds: 15 | 30 | 60;
  autoSkipOptionalFields: boolean;
}

export interface AutonomyPolicy {
  mode: "autonomous" | "strict_control";
  answeringMode?: "competitive" | "conservative";
  freeTextStrategy: "ai_draft" | "profile_only" | "skip_job";
  unknownFieldStrategy: "defer_to_finish_later" | "skip_job" | "pause_campaign";
  aiConfidenceThreshold: number;
  maxThroughput: {
    dailyCap: number;
    hourlyCap: number;
  };
}

export interface StructuredAIAnswerPlan {
  fieldKey: string;
  value: ApplicationAnswerValue;
  optionId?: string;
  confidence: number;
  source: "profile_fact" | "approved_answer" | "ai_text" | "ai_option";
  reason: string;
}

/**
 * Candidate-authored facts that can later be referenced by approved job-search
 * workflows. These values are never inferred or generated by the executor.
 */
export interface CandidateProfile {
  fullName: string;
  contactEmail: string;
  phone: string;
  location: string;
  headline: string;
  summary: string;
  linkedinUrl: string;
  portfolioUrl: string;
  authorizedToWork: CandidateFactStatus;
  requiresSponsorship: CandidateFactStatus;
  autopilot: CandidateAutopilotPreferences;
}

/**
 * Public metadata for one candidate-approved resume. The human-readable file
 * name is also the browser executor's stable LinkedIn selection identity.
 */
export interface ResumeDocumentSummary {
  id: string;
  fileName: string;
  targetRole: string;
  mimeType: "application/pdf";
  byteSize: number;
  contentHash: string;
  version: number;
  isDefault: boolean;
  updatedAt: string;
}

/** Capability-delivered PDF used only by the bound browser execution session. */
export interface ExecutorResumeDocument extends ResumeDocumentSummary {
  bytesBase64: string;
}

export const APPLICATION_QUESTION_CATEGORIES = [
  "full_name",
  "contact_email",
  "phone",
  "location",
  "headline",
  "professional_summary",
  "linkedin_url",
  "portfolio_url",
  "work_authorization",
  "sponsorship",
  "years_experience",
  "education",
  "compensation",
  "availability",
  "security_clearance",
  "legal_attestation",
  "background_check",
  "demographic",
  "disability",
  "veteran_status",
  "consent",
  "open_text",
  "other",
] as const;

export type ApplicationQuestionCategory = (typeof APPLICATION_QUESTION_CATEGORIES)[number];

export const APPLICATION_FIELD_KINDS = [
  "text",
  "textarea",
  "number",
  "single_select",
  "multi_select",
  "radio",
  "checkbox",
] as const;

export type ApplicationFieldKind = (typeof APPLICATION_FIELD_KINDS)[number];

export interface ApplicationFieldOption {
  /** Opaque adapter-generated ID. The model never receives a raw DOM value. */
  id: string;
  label: string;
}

export interface ApplicationFieldConstraints {
  minLength?: number;
  maxLength?: number;
  minimum?: number;
  maximum?: number;
  maxSelections?: number;
}

export interface ApplicationFieldDescriptor {
  key: string;
  question: string;
  kind: ApplicationFieldKind;
  category: ApplicationQuestionCategory;
  required: boolean;
  options: ApplicationFieldOption[];
  constraints?: ApplicationFieldConstraints;
}

export const APPLICATION_ANSWER_STRATEGIES = [
  "deterministic",
  "ai_text",
  "ai_option",
  "user_input",
  "unsupported",
] as const;

export type ApplicationAnswerStrategy = (typeof APPLICATION_ANSWER_STRATEGIES)[number];

export interface ApplicationAnswerPlan {
  strategy: ApplicationAnswerStrategy;
  reason:
    | "candidate_fact_available"
    | "approved_answer_available"
    | "approved_answer_required"
    | "eligible_for_grounded_draft"
    | "eligible_for_constrained_selection"
    | "missing_context"
    | "consequential_question"
    | "sensitive_question"
    | "unknown_question"
    | "unsupported_control";
  candidateFactIds: string[];
  requiresReview: boolean;
}

export type ApplicationAnswerValue =
  | { type: "text"; text: string }
  | { type: "options"; optionIds: string[] }
  | { type: "checked"; checked: boolean };

/**
 * Stored answers use visible option labels rather than a transient site DOM
 * value. A later form can map that label to its fresh opaque option ID.
 */
export type StoredApplicationAnswerValue =
  | { type: "text"; text: string }
  | { type: "options"; optionLabels: string[] }
  | { type: "checked"; checked: boolean };

export const APPLICATION_ANSWER_MEMORY_SCOPES = ["global", "campaign"] as const;

export type ApplicationAnswerMemoryScope = (typeof APPLICATION_ANSWER_MEMORY_SCOPES)[number];

export interface ApplicationAnswerMemory {
  id: string;
  scope: ApplicationAnswerMemoryScope;
  campaignId?: string;
  intentKey: string;
  category: ApplicationQuestionCategory;
  question: string;
  answer: StoredApplicationAnswerValue;
  autoUse: boolean;
  createdAt: string;
  updatedAt: string;
  lastUsedAt?: string;
  useCount: number;
}

export interface ResolvedApplicationAnswer {
  status: "resolved";
  fieldKey: string;
  source: "profile_fact" | "approved_answer" | "ai" | "user";
  answer: ApplicationAnswerValue;
  provenanceIds: string[];
  requiresReview: boolean;
  provider?: string;
  model?: string;
}

export interface UnresolvedApplicationAnswer {
  status: "needs_user_input" | "unsupported";
  fieldKey: string;
  reason: string;
  requiresReview: true;
}

export type ApplicationAnswerDecision =
  | ResolvedApplicationAnswer
  | UnresolvedApplicationAnswer;

/** A durable, value-minimized record of one observed application field. */
export interface ApplicationAnswerPlanRecord {
  id: string;
  runId: string;
  jobExternalId: string;
  observationFingerprint: string;
  field: ApplicationFieldDescriptor;
  plan: ApplicationAnswerPlan;
  decision?: ApplicationAnswerDecision;
  createdAt: string;
  updatedAt: string;
}

export const APPLICATION_INTERVENTION_STATUSES = [
  "pending",
  "answered",
  "deferred",
  "applied",
  "skipped",
] as const;

export type ApplicationInterventionStatus = (typeof APPLICATION_INTERVENTION_STATUSES)[number];

/**
 * A durable, candidate-facing request for one answer. It intentionally stores
 * a field descriptor and verified job reference, not raw third-party DOM.
 */
export interface ApplicationIntervention {
  id: string;
  runId: string;
  jobExternalId: string;
  jobUrl: string;
  jobTitle?: string;
  company?: string;
  observationFingerprint: string;
  field: ApplicationFieldDescriptor;
  status: ApplicationInterventionStatus;
  deadlineAt?: string;
  answer?: ApplicationAnswerValue;
  rememberScope?: ApplicationAnswerMemoryScope;
  autoUse?: boolean;
  createdAt: string;
  updatedAt: string;
  answeredAt?: string;
  deferredAt?: string;
}

export interface ApplicationInterventionResponse {
  answer: ApplicationAnswerValue;
  rememberScope?: ApplicationAnswerMemoryScope;
  autoUse?: boolean;
}

export interface ExecutionCheckpoint {
  name: string;
  attempt: number;
  updatedAt: string;
}

export const EXECUTION_PHASES = [
  "claimed",
  "navigating_to_search",
  "discovering_search",
  "discovery_complete",
  "navigating_to_job",
  "qualifying_job",
  "qualification_complete",
  "opening_application",
  "processing_application",
  "application_retry",
  "awaiting_user",
  "terminal",
] as const;

export type ExecutionPhase = (typeof EXECUTION_PHASES)[number];

/**
 * Explains why a controller is waiting without persisting raw page content.
 * Only an answer-backed wait may be resumed automatically when the dashboard
 * confirms that a queued answer has been supplied. Every other wait requires
 * an explicit candidate action or a fresh campaign decision.
 */
export const AWAITING_USER_CONTEXTS = [
  "application_intervention",
  "resume_selection",
  "final_review",
  "manual_verification",
  "qualification",
  "login_or_security",
  "deferred_question",
] as const;

export type AwaitingUserContext = (typeof AWAITING_USER_CONTEXTS)[number];

export interface BrowserExecutionPlan {
  runId: string;
  adapterId: "linkedin";
  targetRole: string;
  targetLocation: string;
  targetApplications: number;
  poolTarget: number;
  autonomyPolicy?: AutonomyPolicy;
  /**
   * The server derives production submission from the durable campaign
   * policy. `test_submit` is reserved for isolated confirmation-flow testing.
   */
  submissionMode?: "review_only" | "autonomous_submit" | "test_submit";
  preferences: {
    experience: "entry" | "mid" | "senior" | "lead";
    workStyle: "remote" | "hybrid" | "onsite" | "any";
    onlyEasyApply: boolean;
    excludedTerms: string[];
  };
}

export interface DiscoveredJobReference {
  externalId: string;
  url: string;
  title?: string;
  company?: string;
  location?: string;
}

export interface LinkedInDiscoveryState {
  searchUrl: string;
  pageIndex: number;
  maxPages: number;
  poolTarget: number;
  jobs: DiscoveredJobReference[];
}

/**
 * A deliberately small, resumable controller for the first post-discovery
 * checkpoint. It keeps a canonical job reference in extension-private state
 * so page observations can be proved against the job the executor itself
 * navigated to, rather than against whichever LinkedIn page happens to load.
 */
export interface LinkedInQualificationState {
  /** The bounded number of job detail pages this release may inspect. */
  inspectionBudget: number;
  inspectedExternalIds: string[];
  currentJob?: DiscoveredJobReference;
}

export interface ExtensionExecutionSession {
  schemaVersion: 2;
  runId: string;
  claimTicketFingerprint: string;
  executorTabId: number;
  executorSessionId: string;
  executorEventCapability: BrowserExecutorEventCapability;
  controllerOrigin: string;
  state: RunState;
  phase: ExecutionPhase;
  /**
   * Additive so already-installed helpers retain their durable checkpoints.
   * It is deliberately an enum, never a raw third-party page message.
   */
  awaitingUserContext?: AwaitingUserContext;
  run: BrowserRunSummary;
  executionPlan: BrowserExecutionPlan;
  discovery: LinkedInDiscoveryState;
  qualification: LinkedInQualificationState;
  checkpoint: ExecutionCheckpoint;
  profileResumeUploaded?: boolean;
  applicationResume?: {
    jobExternalId: string;
    fileName: string;
  };
  pendingEventIds: string[];
}

export const WEB_BRIDGE_SOURCE = "rapidapply-web";
export const EXTENSION_BRIDGE_SOURCE = "rapidapply-extension";

export interface ExtensionPingMessage {
  source: typeof WEB_BRIDGE_SOURCE;
  type: "EXTENSION_PING";
}

export interface ExtensionReadyMessage {
  source: typeof EXTENSION_BRIDGE_SOURCE;
  type: "EXTENSION_READY";
  version: string;
  activeRunId?: string;
  executionState?: RunState;
}

export interface BrowserExecutionTicket {
  runId: string;
  token: string;
  expiresAt: string;
}

/**
 * An extension-private, short-lived capability for reporting verified executor
 * events for exactly one claimed run. It is never posted back into the web page.
 */
export interface BrowserExecutorEventCapability {
  runId: string;
  token: string;
  expiresAt: string;
}

export interface BrowserRunSummary {
  id: string;
  campaignId: string;
  state: RunState;
  targetRole: string;
  targetLocation: string;
  boardIds: string[];
  targetApplications: number;
  appliedCount: number;
  skippedCount: number;
  executorTabId: number | null;
  startedAt: string | null;
  completedAt: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface ExecutorClaimResponse {
  run: BrowserRunSummary;
  executorEventCapability: BrowserExecutorEventCapability;
  executionPlan: BrowserExecutionPlan;
}

export interface ExtensionRunHandoffMessage {
  source: typeof WEB_BRIDGE_SOURCE;
  type: "EXTENSION_RUN_HANDOFF";
  executionTicket: BrowserExecutionTicket;
}

export interface ExtensionRunClaimedMessage {
  source: typeof EXTENSION_BRIDGE_SOURCE;
  type: "EXTENSION_RUN_CLAIMED";
  run: BrowserRunSummary;
}

export interface ExtensionRunClaimFailedMessage {
  source: typeof EXTENSION_BRIDGE_SOURCE;
  type: "EXTENSION_RUN_CLAIM_FAILED";
  runId: string;
  reason: string;
}

export interface ExtensionRunLaunchAcknowledgementMessage {
  source: typeof WEB_BRIDGE_SOURCE;
  type: "EXTENSION_RUN_LAUNCH_ACKNOWLEDGED";
  runId: string;
}

export interface ExtensionRunStateSyncMessage {
  source: typeof WEB_BRIDGE_SOURCE;
  type: "EXTENSION_RUN_STATE_SYNC";
  runId: string;
  state: "running" | "paused" | "needs_user_input" | "cancelled";
}

/** Sent after an answer is saved from the dashboard so a paired helper can
 * re-observe the current form and resume without a page refresh. */
export interface ExtensionApplicationInterventionsUpdatedMessage {
  source: typeof WEB_BRIDGE_SOURCE;
  type: "EXTENSION_APPLICATION_INTERVENTIONS_UPDATED";
  runId: string;
}

export type BrowserBridgeMessage =
  | ExtensionPingMessage
  | ExtensionReadyMessage
  | ExtensionRunHandoffMessage
  | ExtensionRunClaimedMessage
  | ExtensionRunClaimFailedMessage
  | ExtensionRunLaunchAcknowledgementMessage
  | ExtensionRunStateSyncMessage
  | ExtensionApplicationInterventionsUpdatedMessage;

export function isExtensionReadyMessage(value: unknown): value is ExtensionReadyMessage {
  if (!isRecord(value)) return false;

  return (
    value.source === EXTENSION_BRIDGE_SOURCE &&
    value.type === "EXTENSION_READY" &&
    typeof value.version === "string" &&
    (value.activeRunId === undefined || typeof value.activeRunId === "string") &&
    (value.executionState === undefined || isRunState(value.executionState))
  );
}

export function isBrowserExecutorEventCapability(
  value: unknown,
): value is BrowserExecutorEventCapability {
  if (!isRecord(value)) return false;

  return (
    typeof value.runId === "string" &&
    typeof value.token === "string" &&
    value.token.length >= 32 &&
    typeof value.expiresAt === "string"
  );
}

export function isBrowserExecutionPlan(value: unknown): value is BrowserExecutionPlan {
  if (!isRecord(value) || !isRecord(value.preferences)) return false;

  return (
    typeof value.runId === "string" &&
    value.adapterId === "linkedin" &&
    typeof value.targetRole === "string" &&
    typeof value.targetLocation === "string" &&
    typeof value.targetApplications === "number" &&
    Number.isInteger(value.targetApplications) &&
    value.targetApplications > 0 &&
    typeof value.poolTarget === "number" &&
    Number.isInteger(value.poolTarget) &&
    value.poolTarget >= value.targetApplications &&
    (value.autonomyPolicy === undefined || isAutonomyPolicy(value.autonomyPolicy)) &&
    (value.submissionMode === undefined ||
      value.submissionMode === "review_only" ||
      value.submissionMode === "autonomous_submit" ||
      value.submissionMode === "test_submit") &&
    ["entry", "mid", "senior", "lead"].includes(String(value.preferences.experience)) &&
    ["remote", "hybrid", "onsite", "any"].includes(String(value.preferences.workStyle)) &&
    typeof value.preferences.onlyEasyApply === "boolean" &&
    Array.isArray(value.preferences.excludedTerms) &&
    value.preferences.excludedTerms.every((term) => typeof term === "string")
  );
}

function isAutonomyPolicy(value: unknown): value is AutonomyPolicy {
  if (!isRecord(value) || !isRecord(value.maxThroughput)) return false;
  const throughput = value.maxThroughput;
  return (
    (value.mode === "autonomous" || value.mode === "strict_control") &&
    ["ai_draft", "profile_only", "skip_job"].includes(String(value.freeTextStrategy)) &&
    ["defer_to_finish_later", "skip_job", "pause_campaign"].includes(String(value.unknownFieldStrategy)) &&
    typeof value.aiConfidenceThreshold === "number" &&
    value.aiConfidenceThreshold >= 0 &&
    value.aiConfidenceThreshold <= 1 &&
    Number.isInteger(throughput.dailyCap) &&
    typeof throughput.dailyCap === "number" &&
    throughput.dailyCap > 0 &&
    Number.isInteger(throughput.hourlyCap) &&
    typeof throughput.hourlyCap === "number" &&
    throughput.hourlyCap > 0
  );
}

export function isExecutorResumeDocument(value: unknown): value is ExecutorResumeDocument {
  if (!isRecord(value)) return false;

  return (
    typeof value.id === "string" &&
    typeof value.fileName === "string" &&
    /^[A-Za-z0-9]+(?:_[A-Za-z0-9]+)*_Resume_v[1-9][0-9]*\.pdf$/.test(value.fileName) &&
    typeof value.targetRole === "string" &&
    value.targetRole.length > 0 &&
    value.mimeType === "application/pdf" &&
    typeof value.byteSize === "number" &&
    Number.isInteger(value.byteSize) &&
    value.byteSize > 0 &&
    value.byteSize <= 2_000_000 &&
    typeof value.contentHash === "string" &&
    /^[a-f0-9]{64}$/.test(value.contentHash) &&
    typeof value.version === "number" &&
    Number.isInteger(value.version) &&
    value.version > 0 &&
    typeof value.isDefault === "boolean" &&
    typeof value.updatedAt === "string" &&
    typeof value.bytesBase64 === "string" &&
    value.bytesBase64.length > 0
  );
}

export function isExtensionPingMessage(value: unknown): value is ExtensionPingMessage {
  if (!isRecord(value)) return false;

  return value.source === WEB_BRIDGE_SOURCE && value.type === "EXTENSION_PING";
}

export function isExtensionRunHandoffMessage(value: unknown): value is ExtensionRunHandoffMessage {
  if (!isRecord(value) || !isBrowserExecutionTicket(value.executionTicket)) return false;

  return value.source === WEB_BRIDGE_SOURCE && value.type === "EXTENSION_RUN_HANDOFF";
}

export function isExtensionRunLaunchAcknowledgementMessage(
  value: unknown,
): value is ExtensionRunLaunchAcknowledgementMessage {
  if (!isRecord(value)) return false;

  return (
    value.source === WEB_BRIDGE_SOURCE &&
    value.type === "EXTENSION_RUN_LAUNCH_ACKNOWLEDGED" &&
    typeof value.runId === "string"
  );
}

export function isExtensionRunStateSyncMessage(
  value: unknown,
): value is ExtensionRunStateSyncMessage {
  if (!isRecord(value)) return false;

  return (
    value.source === WEB_BRIDGE_SOURCE &&
    value.type === "EXTENSION_RUN_STATE_SYNC" &&
    typeof value.runId === "string" &&
    ["running", "paused", "needs_user_input", "cancelled"].includes(String(value.state))
  );
}

export function isExtensionApplicationInterventionsUpdatedMessage(
  value: unknown,
): value is ExtensionApplicationInterventionsUpdatedMessage {
  return isRecord(value) &&
    value.source === WEB_BRIDGE_SOURCE &&
    value.type === "EXTENSION_APPLICATION_INTERVENTIONS_UPDATED" &&
    typeof value.runId === "string";
}

export function isExtensionRunClaimedMessage(value: unknown): value is ExtensionRunClaimedMessage {
  if (!isRecord(value) || !isBrowserRunSummary(value.run)) return false;

  return value.source === EXTENSION_BRIDGE_SOURCE && value.type === "EXTENSION_RUN_CLAIMED";
}

export function isExtensionRunClaimFailedMessage(value: unknown): value is ExtensionRunClaimFailedMessage {
  if (!isRecord(value)) return false;

  return (
    value.source === EXTENSION_BRIDGE_SOURCE &&
    value.type === "EXTENSION_RUN_CLAIM_FAILED" &&
    typeof value.runId === "string" &&
    typeof value.reason === "string"
  );
}

export function isBrowserExecutionTicket(value: unknown): value is BrowserExecutionTicket {
  if (!isRecord(value)) return false;

  return (
    typeof value.runId === "string" &&
    typeof value.token === "string" &&
    typeof value.expiresAt === "string"
  );
}

export function isBrowserRunSummary(value: unknown): value is BrowserRunSummary {
  if (!isRecord(value)) return false;

  return (
    typeof value.id === "string" &&
    typeof value.campaignId === "string" &&
    isRunState(value.state) &&
    typeof value.targetRole === "string" &&
    typeof value.targetLocation === "string" &&
    Array.isArray(value.boardIds) &&
    value.boardIds.every((boardId) => typeof boardId === "string") &&
    typeof value.targetApplications === "number" &&
    typeof value.appliedCount === "number" &&
    typeof value.skippedCount === "number" &&
    (typeof value.executorTabId === "number" || value.executorTabId === null) &&
    (typeof value.startedAt === "string" || value.startedAt === null) &&
    (typeof value.completedAt === "string" || value.completedAt === null) &&
    typeof value.createdAt === "string" &&
    typeof value.updatedAt === "string"
  );
}

export function isRunState(value: unknown): value is RunState {
  return typeof value === "string" && (RUN_STATES as readonly string[]).includes(value);
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null;
}
