import {
  APPLICATION_ANSWER_MEMORY_SCOPES,
  APPLICATION_FIELD_KINDS,
  APPLICATION_QUESTION_CATEGORIES,
  EXECUTOR_RUN_EVENT_TYPES,
  RUN_EVENT_TYPES,
} from "@rapidapply/contracts";
import { z } from "zod";

const BOARD_IDS = ["linkedin", "indeed", "monster"] as const;

const advancedConfigurationSchema = z
  .object({
    dailyLimit: z.number().int().min(1).max(100),
    experience: z.enum(["entry", "mid", "senior", "lead"]),
    workStyle: z.enum(["remote", "hybrid", "onsite", "any"]),
    aiTailor: z.boolean(),
    onlyEasyApply: z.boolean(),
    exclude: z.string().max(1_000),
  })
  .strict();

export const autonomyPolicySchema = z
  .object({
    mode: z.enum(["autonomous", "strict_control"]).default("autonomous"),
    freeTextStrategy: z.enum(["ai_draft", "profile_only", "skip_job"]).default("ai_draft"),
    unknownFieldStrategy:
      z.enum(["defer_to_finish_later", "skip_job", "pause_campaign"]).default("defer_to_finish_later"),
    aiConfidenceThreshold: z.number().min(0).max(1).default(0.75),
    maxThroughput: z
      .object({
        dailyCap: z.number().int().min(1).max(100).default(25),
        hourlyCap: z.number().int().min(1).max(20).default(5),
      })
      .default({ dailyCap: 25, hourlyCap: 5 }),
  })
  .strict();

export const createRunInputSchema = z
  .object({
    targetRole: z.string().trim().min(2).max(160),
    targetLocation: z.string().trim().min(2).max(160),
    boardIds: z.array(z.enum(BOARD_IDS)).min(1).max(BOARD_IDS.length),
    targetApplications: z.number().int().min(1).max(100),
    configuration: advancedConfigurationSchema,
    autonomyPolicy: autonomyPolicySchema.optional(),
  })
  .strict()
  .superRefine((value, context) => {
    if (value.targetApplications !== value.configuration.dailyLimit) {
      context.addIssue({
        code: "custom",
        path: ["targetApplications"],
        message: "The application target must match the daily limit.",
      });
    }
  });

export type CreateRunInput = z.infer<typeof createRunInputSchema>;

const eventDetailValueSchema = z.union([z.string(), z.number(), z.boolean(), z.null()]);

export const appendRunEventInputSchema = z
  .object({
    type: z.enum(RUN_EVENT_TYPES),
    idempotencyKey: z.string().trim().min(12).max(160),
    detail: z.record(z.string(), eventDetailValueSchema).optional(),
    occurredAt: z.string().datetime({ offset: true }).optional(),
  })
  .strict()
  .superRefine((value, context) => {
    if (["run_created", "executor_recovery_prepared"].includes(value.type)) {
      context.addIssue({
        code: "custom",
        path: ["type"],
        message: "This event is generated by the server.",
      });
    }

    if (value.detail && Object.keys(value.detail).length > 30) {
      context.addIssue({
        code: "custom",
        path: ["detail"],
        message: "An event can contain at most 30 detail fields.",
      });
    }
  });

export type AppendRunEventInput = z.infer<typeof appendRunEventInputSchema>;

/**
 * The web app may only control a run's lifecycle. Executor-originated events
 * use a separate capability-protected endpoint; accepting them from a general
 * browser session would let the dashboard forge automation progress.
 */
export const userControlledRunEventInputSchema = appendRunEventInputSchema.superRefine(
  (value, context) => {
    if (!["run_paused", "run_resumed", "run_cancelled"].includes(value.type)) {
      context.addIssue({
        code: "custom",
        path: ["type"],
        message: "This event can only be recorded by a verified browser executor.",
      });
    }
  },
);

export type UserControlledRunEventInput = z.infer<typeof userControlledRunEventInputSchema>;

/**
 * Executor events use a separate, extension-private capability. Keeping the
 * credential in the body avoids granting the web dashboard authority to forge
 * progress events through a user's normal session.
 */
export const executorRunEventInputSchema = z
  .object({
    runId: z.string().uuid(),
    executorSessionId: z.string().uuid(),
    executorEventToken: z.string().trim().min(32).max(128),
    type: z.enum(EXECUTOR_RUN_EVENT_TYPES),
    idempotencyKey: z.string().trim().min(12).max(160),
    detail: z.record(z.string(), eventDetailValueSchema).optional(),
    occurredAt: z.string().datetime({ offset: true }).optional(),
  })
  .strict()
  .superRefine((value, context) => {
    if (value.detail && Object.keys(value.detail).length > 30) {
      context.addIssue({
        code: "custom",
        path: ["detail"],
        message: "An event can contain at most 30 detail fields.",
      });
    }
  });

export type ExecutorRunEventInput = z.infer<typeof executorRunEventInputSchema>;

export const executorStatusInputSchema = z
  .object({
    runId: z.string().uuid(),
    executorSessionId: z.string().uuid(),
    executorEventToken: z.string().trim().min(32).max(128),
  })
  .strict();

export type ExecutorStatusInput = z.infer<typeof executorStatusInputSchema>;

const applicationFieldDescriptorSchema = z.object({
  key: z.string().regex(/^[a-f0-9]{8}$/),
  question: z.string().trim().min(1).max(240),
  kind: z.enum(APPLICATION_FIELD_KINDS),
  category: z.enum(APPLICATION_QUESTION_CATEGORIES),
  required: z.boolean(),
  options: z.array(z.object({
    id: z.string().regex(/^[a-f0-9]{8}$/),
    label: z.string().trim().min(1).max(120),
  }).strict()).max(300),
  constraints: z.object({
    minLength: z.number().int().min(0).max(100_000).optional(),
    maxLength: z.number().int().min(0).max(100_000).optional(),
    minimum: z.number().finite().optional(),
    maximum: z.number().finite().optional(),
    maxSelections: z.number().int().min(1).max(20).optional(),
  }).strict().optional(),
}).strict();

const applicationAnswerValueSchema = z.discriminatedUnion("type", [
  z.object({
    type: z.literal("text"),
    text: z.string().trim().min(1).max(4_000),
  }).strict(),
  z.object({
    type: z.literal("options"),
    optionIds: z.array(z.string().regex(/^[a-f0-9]{8}$/)).min(1).max(20),
  }).strict(),
  z.object({
    type: z.literal("checked"),
    checked: z.boolean(),
  }).strict(),
]);

const applicationInterventionResponseSchema = z.object({
  answer: applicationAnswerValueSchema,
  rememberScope: z.enum(APPLICATION_ANSWER_MEMORY_SCOPES).optional(),
  autoUse: z.boolean().optional(),
}).strict();

export const executorApplicationPlanInputSchema = z.object({
  runId: z.string().uuid(),
  executorSessionId: z.string().uuid(),
  executorEventToken: z.string().trim().min(32).max(128),
  jobExternalId: z.string().regex(/^\d+$/).max(30),
  observationFingerprint: z.string().regex(/^[a-f0-9]{8}$/),
  fields: z.array(applicationFieldDescriptorSchema).min(1).max(80),
  jobContext: z.object({
    externalId: z.string().trim().optional(),
    title: z.string().trim().max(240).optional(),
    company: z.string().trim().max(240).optional(),
    location: z.string().trim().max(240).optional(),
    description: z.string().trim().max(8_000).optional(),
    targetRole: z.string().trim().max(160).optional(),
  }).passthrough().optional(),
}).strict();

export type ExecutorApplicationPlanInput = z.infer<typeof executorApplicationPlanInputSchema>;

const executorAuthoritySchema = z.object({
  runId: z.string().uuid(),
  executorSessionId: z.string().uuid(),
  executorEventToken: z.string().trim().min(32).max(128),
}).strict();

export const executorResumeInputSchema = executorAuthoritySchema;

export type ExecutorResumeInput = z.infer<typeof executorResumeInputSchema>;

export const executorApplicationInterventionsInputSchema = executorAuthoritySchema.extend({
  jobExternalId: z.string().regex(/^\d+$/).max(30),
  observationFingerprint: z.string().regex(/^[a-f0-9]{8}$/),
  jobUrl: z.string().url().max(500).refine((value) => {
    try {
      const url = new URL(value);
      return url.protocol === "https:" && url.hostname === "www.linkedin.com" &&
        (url.pathname.startsWith("/jobs/view") || url.pathname.startsWith("/jobs/search"));
    } catch {
      return false;
    }
  }, "The application reference must be a LinkedIn job URL."),
  jobTitle: z.string().trim().max(240).optional(),
  company: z.string().trim().max(240).optional(),
}).strict();

export type ExecutorApplicationInterventionsInput = z.infer<typeof executorApplicationInterventionsInputSchema>;

export const executorApplicationInterventionActionInputSchema = executorAuthoritySchema.extend({
  action: z.enum(["answer", "defer", "touch"]),
  response: applicationInterventionResponseSchema.optional(),
}).strict().superRefine((value, context) => {
  if (value.action === "answer" && !value.response) {
    context.addIssue({
      code: "custom",
      path: ["response"],
      message: "An answer is required for this application question.",
    });
  }
  if (value.action !== "answer" && value.response) {
    context.addIssue({
      code: "custom",
      path: ["response"],
      message: "Only an answer action may include a response.",
    });
  }
});

export type ExecutorApplicationInterventionActionInput = z.infer<typeof executorApplicationInterventionActionInputSchema>;

export const userApplicationInterventionResponseInputSchema = applicationInterventionResponseSchema;

export type UserApplicationInterventionResponseInput = z.infer<typeof userApplicationInterventionResponseInputSchema>;

export const deferExecutorJobInputSchema = executorAuthoritySchema.extend({
  jobExternalId: z.string().trim().min(1).max(100),
  url: z.string().url().max(500),
  title: z.string().trim().min(1).max(240),
  company: z.string().trim().min(1).max(240),
  reasonCode: z.string().trim().min(1).max(100),
  reasonDetails: z.string().trim().max(1000).optional(),
}).strict();

export type DeferExecutorJobInput = z.infer<typeof deferExecutorJobInputSchema>;

export const resumeAuditInputSchema = executorAuthoritySchema.extend({
  existingFileNames: z.array(z.string().trim().min(1).max(240)).max(100),
}).strict();

export type ResumeAuditInput = z.infer<typeof resumeAuditInputSchema>;

export const claimExecutorInputSchema = z
  .object({
    runId: z.string().uuid(),
    executionTicket: z.string().trim().min(32).max(128),
    executorSessionId: z.string().uuid(),
    executorTabId: z.number().int().min(0).max(2_147_483_647),
    extensionVersion: z.string().trim().min(1).max(32),
  })
  .strict();

export type ClaimExecutorInput = z.infer<typeof claimExecutorInputSchema>;

export const prepareExecutorInputSchema = z
  .object({
    recover: z.boolean().optional().default(false),
  })
  .strict();

export type PrepareExecutorInput = z.infer<typeof prepareExecutorInputSchema>;
